### ISSUE TITLE
Tabbed Layout

### ISSUE THREAD

**Issue by daniel-centore** [me-next/menext-app#1]
Make basic tabbed layout with the following tabs:

- **Home**: Create/Join Event. Settings.
- **Library**: Current user's music library (if applicable) (_ex_ playlists, artists, songs)
- **Playing**: Currently playing song along with skip, volume control, etc
- **Search**: Searches the entire Spotify catalogue
- **Queue**: Suggestions & Next Up Queues

**Comment by ConnorFoody** [comment]
Do we need any custom graphics for each of these?

**Comment by daniel-centore** [comment]
I think for now we'll just write the text, no?
