### ISSUE TITLE
Create the song list UI element

### ISSUE THREAD

**Issue by daniel-centore** [me-next/menext-app#11]
This UI element should be a scrollable list of songs. It needs to work in both iOS and Android.

Features
- Song name and artist
- Menu
- Multi-select

Features which can be turned on and off:
- Drag to reorder

**Comment by daniel-centore** [comment]
This should probably use something like https://github.com/pnavk/Drag-and-Drop-ListView as a base. I'm thinking that it should have multiple modes so we can turn on/off library view, play next queue, and suggestions queue. Also, it would be easy to make drag+drop suggestions/play next queue by combining them into one giant UI list element where there is a labeled separator cell between the two actual queues. Then just parse the data properly whenever the list changes.

Perhaps library and queues should be two different classes extending the aforementioned project...

**Comment by ConnorFoody** [comment]
@daniel-centore I think this is done?

**Comment by daniel-centore** [comment]
* Include artist
* Multi select
* Use `ISong` instead

**Comment by ConnorFoody** [comment]
Kk, I'll fix once all the PRs are in. Should it use some generic instead of ```ISong```?

When do we want to use multi select?

**Comment by daniel-centore** [comment]
> Should it use some generic instead of `ISong`?

When would we need to be more generic than `ISong`?

> When do we want to use multi select?

We always want to use multi select, no? Suggesting, Moving to Play Next, Removing, Ranking, etc. are all things where usability is improved by allowing users to select multiple items first.

**Comment by ConnorFoody** [comment]
> When would we need to be more generic than ISong?

Do we want to provide albums / artists on the search screen that you can navigate to? 

> We always want to use multi select, no?

I don't think we want to do multi-select within a search? How would we provide a UI that is consistent for multi-select ranking?

I think that multi-select makes sense for moving to play next and removing.

**Comment by daniel-centore** [comment]
> Do we want to provide albums / artists on the search screen that you can navigate to?

For now I think we're just going to show song results. Adding other types makes things complicated.

**Edit:** As for navigation, wouldn't that be better served with a different list type?

> I don't think we want to do multi-select within a search?

Why not? I might search for "Journey" and add "Don't Stop Believin" and "Anyway you want it"

> How would we provide a UI that is consistent for multi-select ranking?

Ranking should probably have buttons on the items, so nvm on that one.

**Comment by ConnorFoody** [comment]
> For now I think we're just going to show song results. Adding other types makes things complicated.

Sounds like a plan

> Edit: As for navigation, wouldn't that be better served with a different list type?

Yeah

> Why not? I might search for "Journey" and add "Don't Stop Believin" and "Anyway you want it"

This use case makes sense.

As an aside, it seems like we would need to do our own search ordering for this.

**Comment by daniel-centore** [comment]
> As an aside, it seems like we would need to do our own search ordering for this.

For what reason?
