### ISSUE TITLE
Communicate with backend

### ISSUE THREAD

**Issue by daniel-centore** [me-next/menext-app#16]
Write a class which has functions mapping to the backend API

**Comment by daniel-centore** [comment]
* Create a new git repo
* Use Mono Studio

**Comment by daniel-centore** [comment]
@samsaksfithian we decided to assign this to @mluquette since he can work on it using Mono Studio, which is available in Windows

**Comment by daniel-centore** [comment]
You're going to create a General --> Shared Project for the main library, and a .NET --> Console Project for the Unit Testing. Be aware that you need to create a Console Project and reference the Shared Project, otherwise the Shared Project will never get compiled and you won't even get syntax error feedback.

**Comment by ConnorFoody** [comment]
Is this a duplicate of #12?

**Comment by daniel-centore** [comment]
Yes. Not sure what I was smoking there. This one has more info so I closed the o/ one.

**Comment by daniel-centore** [comment]
We've decided to abandon using Mono Studio for this as having another dependency project will just add more to the mess. Just create a new folder in the main MeNext project called `Backend`.

We should be able to utilise a class there which implements all the basic functionality available in `MainController`. There is no need to do any threading; that will be handled by MainController in the future, although it should still be thread safe, (_ie_ synchronisation on any concurrent object access should be explicit, or we should only be using thread-safe objects).

**Comment by daniel-centore** [comment]
@ConnorFoody Completed? Just make new issues as we need more of the API implemented?

**Comment by ConnorFoody** [comment]
yeah, like we did on the backend API endpoints
