### ISSUE TITLE
Add Logo

### ISSUE THREAD

**Issue by daniel-centore** [me-next/menext-app#4]
Resize as appropriate and add the logo for iOS and Android

**Comment by samsaksfithian** [comment]
#5 Done

**Comment by daniel-centore** [comment]
@samsaksfithian Looks like you did the logo with text for Android. Could you please fix?
![screen shot 2017-02-23 at 9 34 27 pm](https://cloud.githubusercontent.com/assets/569864/23288177/ee0ca478-fa0f-11e6-96bc-b105fef48a84.png)

**Comment by samsaksfithian** [comment]
Oh, oops. I fixed it now, it just needs to be approved (#6)
