### ISSUE TITLE
Automated UI Testing

### ISSUE THREAD

**Issue by daniel-centore** [me-next/menext-app#41]
Have automated UI testing which generates screenshots for all app pages on several common device sizes (_ex_ iPad, iPad mini, iPhone, Android tablet, Android phone)

Relevant tutorial: https://developer.xamarin.com/guides/testcloud/uitest/intro-to-uitest/

**Comment by ConnorFoody** [comment]
Some things to check would be: 
* Is this free?
* Do we need to change the structure of our code to run this? (mocks, XAML etc)
* What quality of life improvements do we need to make?
