### ISSUE TITLE
Actually Join/End Event

### ISSUE THREAD

**Issue by daniel-centore** [me-next/menext-app#43]
This should properly activate and deactivate relevant tabs as well as making sure that the full process works on the server side.

**Comment by daniel-centore** [comment]
If the server decides to end an event, that should work too (_ex_ if somebody else has ended the event)

**Comment by ConnorFoody** [comment]
Think this is closed, see:
[remove party](https://github.com/me-next/menext-backend/blob/develop/server/server.go#L222)
[leave party](https://github.com/me-next/menext-backend/blob/develop/server/server.go#L188)

**Comment by daniel-centore** [comment]
Not closed. It's not implemented app side yet. See MainController `RequestEndEvent` and `LeaveEvent`.

**Comment by ConnorFoody** [comment]
Oops, thought this was a backend issue. I'll take care of this when I do permissions

**Comment by daniel-centore** [comment]
Btw, this includes making sure that the clients peace elegantly when host ends the event

**Comment by daniel-centore** [comment]
Looks like this is fixed
