### ISSUE TITLE
extract a user ID

### ISSUE THREAD

**Issue by ConnorFoody** [me-next/menext-app#51]
Need to get some unique identifier for that can't easily be guessed (ie not an email address, but a hashed email would be OK)

**Comment by daniel-centore** [comment]
Why can't we just produce a secure random string when the user logs in?

Is this a duplicate of https://github.com/me-next/menext-backend/issues/21 ?

**Comment by ConnorFoody** [comment]
Yup, it's a duplicate, good find. Lets just generate a string.

**Comment by daniel-centore** [comment]
I suppose it's not exactly a duplicate, since the other one is for generating the string server-side and we can treat this as the issue for actually using in client-side.

**Comment by ConnorFoody** [comment]
Yeah, then we should get rid of the other one.
